Added make as a dependency

diff --git a/Components/Misc/update-themes b/Components/Misc/update-themes
--- a/Components/Misc/update-themes
+++ b/Components/Misc/update-themes
@@ -25,6 +25,10 @@ checkDeps() {
       echo "Sed missing"
       depMissing="true"
     fi
+    if ! command -v make > /dev/null 2>&1; then
+      echo "Make missing"
+      depMissing="true"
+    fi
     if ! git --version > /dev/null 2>&1; then
       echo "Git missing"
       depMissing="true"
